/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [7.03KB] > E:\My Projects\Github\r3f-3\public\scene-transformed.glb [868.93KB] (-12260%)
Author: harb-ayyad (https://sketchfab.com/harb-ayyad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-hoodie-3d-model-fd8d10eb5f5748e581ca6bd0db2abcce
Title: t shirt hoodie 3d model
*/

import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

import { useCustomization } from "../context/Customization";
export function Scene(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  const { material, shoesColor } = useCustomization();

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[-0.01, -0.2, 0.065]} rotation={[1.595, -0.05, 0.012]} scale={0.055} castShadow>
      <meshStandardMaterial
          castShadow
          color={shoesColor.color}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
